# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\allclients.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AllClientsWindow(object):
    def setupUi(self, AllClientsWindow):
        AllClientsWindow.setObjectName("AllClientsWindow")
        AllClientsWindow.resize(782, 695)
        self.centralwidget = QtWidgets.QWidget(AllClientsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableAllClients = QtWidgets.QTableWidget(self.centralwidget)
        self.tableAllClients.setObjectName("tableAllClients")
        self.tableAllClients.setColumnCount(0)
        self.tableAllClients.setRowCount(0)
        self.verticalLayout.addWidget(self.tableAllClients)
        self.tableDeleteOrCreate = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableDeleteOrCreate.sizePolicy().hasHeightForWidth())
        self.tableDeleteOrCreate.setSizePolicy(sizePolicy)
        self.tableDeleteOrCreate.setMinimumSize(QtCore.QSize(0, 192))
        self.tableDeleteOrCreate.setObjectName("tableDeleteOrCreate")
        self.tableDeleteOrCreate.setColumnCount(0)
        self.tableDeleteOrCreate.setRowCount(0)
        self.verticalLayout.addWidget(self.tableDeleteOrCreate)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCreate = QtWidgets.QPushButton(self.centralwidget)
        self.btnCreate.setObjectName("btnCreate")
        self.horizontalLayout.addWidget(self.btnCreate)
        self.btnDelete = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout.addWidget(self.btnDelete)
        self.verticalLayout.addLayout(self.horizontalLayout)
        AllClientsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AllClientsWindow)
        QtCore.QMetaObject.connectSlotsByName(AllClientsWindow)

    def retranslateUi(self, AllClientsWindow):
        _translate = QtCore.QCoreApplication.translate
        AllClientsWindow.setWindowTitle(_translate("AllClientsWindow", "MainWindow"))
        self.label.setText(_translate("AllClientsWindow", "Клиенты"))
        self.btnCreate.setText(_translate("AllClientsWindow", "Создать"))
        self.btnDelete.setText(_translate("AllClientsWindow", "Удалить"))
