# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthWindow(object):
    def setupUi(self, AuthWindow):
        AuthWindow.setObjectName("AuthWindow")
        AuthWindow.resize(456, 202)
        self.centralwidget = QtWidgets.QWidget(AuthWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineLogin.setObjectName("lineLogin")
        self.horizontalLayout.addWidget(self.lineLogin)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnEnter = QtWidgets.QPushButton(self.centralwidget)
        self.btnEnter.setObjectName("btnEnter")
        self.horizontalLayout.addWidget(self.btnEnter)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.linePass = QtWidgets.QLineEdit(self.centralwidget)
        self.linePass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.linePass.setPlaceholderText("")
        self.linePass.setClearButtonEnabled(False)
        self.linePass.setObjectName("linePass")
        self.horizontalLayout_2.addWidget(self.linePass)
        self.radioBtnShowPass = QtWidgets.QRadioButton(self.centralwidget)
        self.radioBtnShowPass.setObjectName("radioBtnShowPass")
        self.horizontalLayout_2.addWidget(self.radioBtnShowPass)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 2)
        AuthWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AuthWindow)
        QtCore.QMetaObject.connectSlotsByName(AuthWindow)

    def retranslateUi(self, AuthWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthWindow.setWindowTitle(_translate("AuthWindow", "MainWindow"))
        self.label.setText(_translate("AuthWindow", "Логин"))
        self.btnEnter.setText(_translate("AuthWindow", "Войти"))
        self.label_2.setText(_translate("AuthWindow", "Пароль"))
        self.radioBtnShowPass.setText(_translate("AuthWindow", "Показать пароль"))
        self.label_3.setText(_translate("AuthWindow", "Авторизация"))
