# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\daily_earnings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DailyEarningsWindow(object):
    def setupUi(self, DailyEarningsWindow):
        DailyEarningsWindow.setObjectName("DailyEarningsWindow")
        DailyEarningsWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(DailyEarningsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidgetDailyEarnigs = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetDailyEarnigs.setObjectName("tableWidgetDailyEarnigs")
        self.tableWidgetDailyEarnigs.setColumnCount(0)
        self.tableWidgetDailyEarnigs.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidgetDailyEarnigs)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout.addWidget(self.calendarWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBoxBath = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxBath.sizePolicy().hasHeightForWidth())
        self.comboBoxBath.setSizePolicy(sizePolicy)
        self.comboBoxBath.setObjectName("comboBoxBath")
        self.verticalLayout.addWidget(self.comboBoxBath)
        self.btnUpdateAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnUpdateAdd.setObjectName("btnUpdateAdd")
        self.verticalLayout.addWidget(self.btnUpdateAdd)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        DailyEarningsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(DailyEarningsWindow)
        QtCore.QMetaObject.connectSlotsByName(DailyEarningsWindow)

    def retranslateUi(self, DailyEarningsWindow):
        _translate = QtCore.QCoreApplication.translate
        DailyEarningsWindow.setWindowTitle(_translate("DailyEarningsWindow", "Дневная выручка"))
        self.label.setText(_translate("DailyEarningsWindow", "Выберете бассейн и доступную дату,\n"
"для который хотите получить информацию о выручке.\n"
" Если отчет был уже создан, то вы можете его обновить,\n"
"но это не рекомендуется, так как они создаются\n"
"автомтически"))
        self.btnUpdateAdd.setText(_translate("DailyEarningsWindow", "Обновить/Добавить данные"))
