# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\menu_for_client.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuForClientWindow(object):
    def setupUi(self, MenuForClientWindow):
        MenuForClientWindow.setObjectName("MenuForClientWindow")
        MenuForClientWindow.resize(715, 286)
        self.centralwidget = QtWidgets.QWidget(MenuForClientWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnGoToPerson = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGoToPerson.sizePolicy().hasHeightForWidth())
        self.btnGoToPerson.setSizePolicy(sizePolicy)
        self.btnGoToPerson.setObjectName("btnGoToPerson")
        self.horizontalLayout.addWidget(self.btnGoToPerson)
        self.btnGoToTickets = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGoToTickets.sizePolicy().hasHeightForWidth())
        self.btnGoToTickets.setSizePolicy(sizePolicy)
        self.btnGoToTickets.setObjectName("btnGoToTickets")
        self.horizontalLayout.addWidget(self.btnGoToTickets)
        self.btnGoToTraining = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGoToTraining.sizePolicy().hasHeightForWidth())
        self.btnGoToTraining.setSizePolicy(sizePolicy)
        self.btnGoToTraining.setObjectName("btnGoToTraining")
        self.horizontalLayout.addWidget(self.btnGoToTraining)
        MenuForClientWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MenuForClientWindow)
        QtCore.QMetaObject.connectSlotsByName(MenuForClientWindow)

    def retranslateUi(self, MenuForClientWindow):
        _translate = QtCore.QCoreApplication.translate
        MenuForClientWindow.setWindowTitle(_translate("MenuForClientWindow", "Меню"))
        self.btnGoToPerson.setText(_translate("MenuForClientWindow", "Моя\n"
" карточка"))
        self.btnGoToTickets.setText(_translate("MenuForClientWindow", "Билеты"))
        self.btnGoToTraining.setText(_translate("MenuForClientWindow", "Мои\n"
" тренировки"))
