# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\menu_for_administraion.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuForAdministatorWindow(object):
    def setupUi(self, MenuForAdministatorWindow):
        MenuForAdministatorWindow.setObjectName("MenuForAdministatorWindow")
        MenuForAdministatorWindow.resize(715, 286)
        self.centralwidget = QtWidgets.QWidget(MenuForAdministatorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnClients = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClients.sizePolicy().hasHeightForWidth())
        self.btnClients.setSizePolicy(sizePolicy)
        self.btnClients.setObjectName("btnClients")
        self.horizontalLayout.addWidget(self.btnClients)
        self.btnDailyEarnings = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDailyEarnings.sizePolicy().hasHeightForWidth())
        self.btnDailyEarnings.setSizePolicy(sizePolicy)
        self.btnDailyEarnings.setObjectName("btnDailyEarnings")
        self.horizontalLayout.addWidget(self.btnDailyEarnings)
        self.btnPaymentTransactions = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPaymentTransactions.sizePolicy().hasHeightForWidth())
        self.btnPaymentTransactions.setSizePolicy(sizePolicy)
        self.btnPaymentTransactions.setObjectName("btnPaymentTransactions")
        self.horizontalLayout.addWidget(self.btnPaymentTransactions)
        self.btnSwimmingSessions = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSwimmingSessions.sizePolicy().hasHeightForWidth())
        self.btnSwimmingSessions.setSizePolicy(sizePolicy)
        self.btnSwimmingSessions.setObjectName("btnSwimmingSessions")
        self.horizontalLayout.addWidget(self.btnSwimmingSessions)
        MenuForAdministatorWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MenuForAdministatorWindow)
        QtCore.QMetaObject.connectSlotsByName(MenuForAdministatorWindow)

    def retranslateUi(self, MenuForAdministatorWindow):
        _translate = QtCore.QCoreApplication.translate
        MenuForAdministatorWindow.setWindowTitle(_translate("MenuForAdministatorWindow", "Меню"))
        self.btnClients.setText(_translate("MenuForAdministatorWindow", "Клиенты"))
        self.btnDailyEarnings.setText(_translate("MenuForAdministatorWindow", "Дневная\n"
"выручка"))
        self.btnPaymentTransactions.setText(_translate("MenuForAdministatorWindow", "Платежные\n"
"транзакции"))
        self.btnSwimmingSessions.setText(_translate("MenuForAdministatorWindow", "Сеансы бассейнов"))
