# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tickets.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TicketWindow(object):
    def setupUi(self, TicketWindow):
        TicketWindow.setObjectName("TicketWindow")
        TicketWindow.resize(832, 476)
        self.centralwidget = QtWidgets.QWidget(TicketWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.labelWorkload = QtWidgets.QLabel(self.centralwidget)
        self.labelWorkload.setObjectName("labelWorkload")
        self.gridLayout.addWidget(self.labelWorkload, 6, 4, 1, 1)
        self.labelPrice = QtWidgets.QLabel(self.centralwidget)
        self.labelPrice.setObjectName("labelPrice")
        self.gridLayout.addWidget(self.labelPrice, 7, 3, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 1, 1, 2)
        self.comboBoxBath = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxBath.setObjectName("comboBoxBath")
        self.gridLayout.addWidget(self.comboBoxBath, 1, 2, 1, 4)
        self.comboBoxPricePolicy = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxPricePolicy.setObjectName("comboBoxPricePolicy")
        self.gridLayout.addWidget(self.comboBoxPricePolicy, 2, 2, 1, 4)
        self.btnBuyTicket = QtWidgets.QPushButton(self.centralwidget)
        self.btnBuyTicket.setObjectName("btnBuyTicket")
        self.gridLayout.addWidget(self.btnBuyTicket, 7, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 5)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.tableWidgetMyTickets = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetMyTickets.setObjectName("tableWidgetMyTickets")
        self.tableWidgetMyTickets.setColumnCount(0)
        self.tableWidgetMyTickets.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidgetMyTickets, 2, 0, 5, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 1, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.comboBoxAvalibleSessions = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxAvalibleSessions.setObjectName("comboBoxAvalibleSessions")
        self.gridLayout.addWidget(self.comboBoxAvalibleSessions, 5, 3, 1, 3)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.calendarWidget, 4, 2, 1, 4)
        TicketWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TicketWindow)
        QtCore.QMetaObject.connectSlotsByName(TicketWindow)

    def retranslateUi(self, TicketWindow):
        _translate = QtCore.QCoreApplication.translate
        TicketWindow.setWindowTitle(_translate("TicketWindow", "MainWindow"))
        self.labelWorkload.setText(_translate("TicketWindow", "*"))
        self.labelPrice.setText(_translate("TicketWindow", "0 р."))
        self.label_4.setText(_translate("TicketWindow", "Выберете сеанс среди доступных"))
        self.btnBuyTicket.setText(_translate("TicketWindow", "Купить"))
        self.label_7.setText(_translate("TicketWindow", "Выберете все пункты, чтобы купить билет"))
        self.label_6.setText(_translate("TicketWindow", "Купленные билеты"))
        self.label_3.setText(_translate("TicketWindow", "Выберете дату среди доступных"))
        self.label_8.setText(_translate("TicketWindow", "Загруженность на данный момент покупки"))
        self.label_5.setText(_translate("TicketWindow", "Цена:"))
        self.label.setText(_translate("TicketWindow", "Выберете бассейн"))
        self.label_2.setText(_translate("TicketWindow", "Выберете тариф"))
