# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\transactions.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PaymentTransactionsWindow(object):
    def setupUi(self, PaymentTransactionsWindow):
        PaymentTransactionsWindow.setObjectName("PaymentTransactionsWindow")
        PaymentTransactionsWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(PaymentTransactionsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableTransactions = QtWidgets.QTableWidget(self.centralwidget)
        self.tableTransactions.setObjectName("tableTransactions")
        self.tableTransactions.setColumnCount(0)
        self.tableTransactions.setRowCount(0)
        self.verticalLayout.addWidget(self.tableTransactions)
        self.btnUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.btnUpdate.setObjectName("btnUpdate")
        self.verticalLayout.addWidget(self.btnUpdate)
        PaymentTransactionsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(PaymentTransactionsWindow)
        QtCore.QMetaObject.connectSlotsByName(PaymentTransactionsWindow)

    def retranslateUi(self, PaymentTransactionsWindow):
        _translate = QtCore.QCoreApplication.translate
        PaymentTransactionsWindow.setWindowTitle(_translate("PaymentTransactionsWindow", "Транзакции"))
        self.label.setText(_translate("PaymentTransactionsWindow", "Транзакции"))
        self.btnUpdate.setText(_translate("PaymentTransactionsWindow", "Обновить"))
